name: dotfiles
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Git reference (branch, tag, or sha1)
        required: false
        default: master
  push:
  release:
    types: [created]

jobs:
  build-and-export-dotfiles:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: install DeterminateSystems Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: build dotfiles from NixOS config
        run: |
          nix build .#dotfiles.los-t14 --print-out-paths

      - name: check generated dotfiles
        run: |
          echo "=== Dereferencing home-files symlink ==="
          ls -la result/home-files/
          echo ""
          echo "=== What's in .config ==="
          ls -la result/home-files/.config/
          echo ""
          echo "=== What's in helix directory (sample) ==="
          ls -la result/home-files/.config/helix/
          echo ""
          echo "=== What's in alacritty directory (sample) ==="
          ls -la result/home-files/.config/alacritty/
          echo ""
          echo "=== Finding ALL items (including symlinks) ==="
          find result/home-files/.config -type f -o -type l | head -30
          echo ""
          echo "=== Total files (regular files only) ==="
          find result/home-files/.config -type f | wc -l
          echo ""
          echo "=== Total symlinks ==="
          find result/home-files/.config -type l | wc -l

      - name: prepare dotfiles for upload
        run: |
          # Copy .config to a regular directory (not Nix store symlinks)
          # This ensures upload-artifact can properly access all files
          mkdir -p dotfiles-export
          cp -rL result/home-files/.config dotfiles-export/
          echo "=== Copied directories ==="
          du -sh dotfiles-export/.config
          ls -la dotfiles-export/.config/ | head -20
          echo ""
          echo "=== What's in copied helix directory ==="
          ls -la dotfiles-export/.config/helix/
          echo ""
          echo "=== What's in copied alacritty directory ==="
          ls -la dotfiles-export/.config/alacritty/
          echo ""
          echo "=== Total files after copy ==="
          find dotfiles-export/.config -type f | wc -l
          echo ""
          echo "=== Sample files after copy ==="
          find dotfiles-export/.config -type f | head -10

      - name: upload dotfiles
        uses: actions/upload-artifact@v4
        with:
          name: los-dotfiles
          path: dotfiles-export/.config

