name: dotfiles
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Git reference (branch, tag, or sha1)
        required: false
        default: master
  push:
  release:
    types: [created]

jobs:
  build-and-export-dotfiles:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: install DeterminateSystems Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: build dotfiles from NixOS config
        run: |
          nix build .#dotfiles.los-t14 --print-out-paths

      - name: show generated configs
        run: |
          echo "=== Generated .config structure ==="
          ls -la result/home-files/.config/
          echo ""
          echo "=== Config directories ==="
          find result/home-files/.config -maxdepth 1 -type d | sort
          echo ""
          echo "=== Total files in .config ==="
          find result/home-files/.config -type f | wc -l

      - name: upload dotfiles
        uses: actions/upload-artifact@v4
        with:
          name: los-dotfiles
          path: result/home-files/.config

