name: test flake
on:
  push:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Git reference (branch, tag, or sha1)
        required: false
        default: master

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: install DeterminateSystems Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: test nix build
        run: |
          nix eval .#nixosConfigurations.los-t14.config.system.build.toplevel

      - name: pr number
        run: echo Pull request number is ${{ steps.update.outputs.pull-request-number }}.
